import { GROUND_TINT_EDGE_FEATHER_PX, GROUND_TINT_GRADIENT_ANGLE_MAX_DEG, GROUND_TINT_GRADIENT_ANGLE_MIN_DEG, GROUND_TINT_TEXTURE_CONTRAST, GROUND_TINT_TEXTURE_HUE_SHIFT_DEG, GROUND_TINT_TEXTURE_LAYER_COUNT, GROUND_TINT_TEXTURE_OFFSET_METERS, GROUND_TINT_TEXTURE_SCALE_MAX, GROUND_TINT_TEXTURE_SCALE_MIN, TINT_DEBUG_COLORS } from '../../config/mapDemoTuning';

const TEXTURE_URLS = ['/tints/watercolor-blob-1.png', '/tints/watercolor-sweep-2.png', '/tints/watercolor-splatter-3.png', '/tints/watercolor-cloud-4.png'] as const;
export type GroundTintTextureLayer = { gradientColors: readonly string[]; gradientAngleDegrees: number; textureUrl: string; offsetXmeters: number; offsetYmeters: number; rotationDegrees: number; scaleX: number; scaleY: number; };
const rasterCache = new Map<string, Promise<HTMLCanvasElement>>();

function seededRandom(seedText: string, salt: number): number { let value = 2166136261 ^ salt; for (let index = 0; index < seedText.length; index += 1) value = Math.imul(value ^ seedText.charCodeAt(index), 16777619); value ^= value >>> 16; value = Math.imul(value, 2246822507); value ^= value >>> 13; value = Math.imul(value, 3266489909); value ^= value >>> 16; return (value >>> 0) / 4294967296; }
function clamp(value: number, minimum: number, maximum: number) { return Math.min(maximum, Math.max(minimum, value)); }
function toHsl(color: string): { hue: number; saturation: number; lightness: number } | null { const match = color.match(/^#([\da-f]{6})$/i); if (!match) return null; const rgb = [0, 2, 4].map((start) => Number.parseInt(match[1].slice(start, start + 2), 16) / 255); const max = Math.max(...rgb), min = Math.min(...rgb), lightness = (max + min) / 2; if (max === min) return { hue: 0, saturation: 0, lightness: lightness * 100 }; const delta = max - min, saturation = delta / (1 - Math.abs(2 * lightness - 1)); const hue = max === rgb[0] ? ((rgb[1] - rgb[2]) / delta) % 6 : max === rgb[1] ? (rgb[2] - rgb[0]) / delta + 2 : (rgb[0] - rgb[1]) / delta + 4; return { hue: (hue * 60 + 360) % 360, saturation: saturation * 100, lightness: lightness * 100 }; }
function shiftHue(color: string, degrees: number) { const hsl = toHsl(color); return hsl ? `hsl(${(hsl.hue + degrees + 360) % 360} ${hsl.saturation}% ${hsl.lightness}%)` : color; }

export function createGroundTintTextureLayers(momentId: string, palette: readonly string[]): GroundTintTextureLayer[] { const count = clamp(Math.round(GROUND_TINT_TEXTURE_LAYER_COUNT), 2, 3); return Array.from({ length: count }, (_, index) => { const textureIndex = (Math.floor(seededRandom(momentId, 10) * TEXTURE_URLS.length) + index) % TEXTURE_URLS.length; const hueOffset = (seededRandom(momentId, 20 + index) * 2 - 1) * GROUND_TINT_TEXTURE_HUE_SHIFT_DEG; const scale = GROUND_TINT_TEXTURE_SCALE_MIN + seededRandom(momentId, 50 + index) * (GROUND_TINT_TEXTURE_SCALE_MAX - GROUND_TINT_TEXTURE_SCALE_MIN); const baseColors = TINT_DEBUG_COLORS ?? palette; return { gradientColors: [0, 1, 2].map((colorIndex) => shiftHue(baseColors[colorIndex % baseColors.length] ?? 'hsl(42 12% 82%)', TINT_DEBUG_COLORS ? 0 : hueOffset)), gradientAngleDegrees: GROUND_TINT_GRADIENT_ANGLE_MIN_DEG + seededRandom(momentId, 80 + index) * (GROUND_TINT_GRADIENT_ANGLE_MAX_DEG - GROUND_TINT_GRADIENT_ANGLE_MIN_DEG), textureUrl: TEXTURE_URLS[textureIndex], offsetXmeters: (seededRandom(momentId, 30 + index) * 2 - 1) * GROUND_TINT_TEXTURE_OFFSET_METERS, offsetYmeters: (seededRandom(momentId, 40 + index) * 2 - 1) * GROUND_TINT_TEXTURE_OFFSET_METERS, rotationDegrees: Math.round(seededRandom(momentId, 60 + index) * 360), scaleX: (seededRandom(momentId, 70 + index) > .5 ? -1 : 1) * scale, scaleY: scale }; }); }
function loadImage(url: string): Promise<HTMLImageElement> { return new Promise((resolve, reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = () => reject(new Error(`Unable to load watercolor texture: ${url}`)); image.src = url; }); }
function gradient(context: CanvasRenderingContext2D, colors: readonly string[], angleDegrees: number, width: number, height: number) { const angle = angleDegrees * Math.PI / 180, radius = Math.hypot(width, height) / 2, x = width / 2, y = height / 2; const fill = context.createLinearGradient(x - Math.cos(angle) * radius, y - Math.sin(angle) * radius, x + Math.cos(angle) * radius, y + Math.sin(angle) * radius); colors.forEach((color, index) => fill.addColorStop(index / Math.max(colors.length - 1, 1), color)); return fill; }
/** GPU/canvas-compositor tinting: no pixel reads, PNG encoding, or decoding round trip. */
function composeTexture(texture: CanvasImageSource, colors: readonly string[], angleDegrees: number, width: number, height: number) { const mask = document.createElement('canvas'); mask.width = width; mask.height = height; const maskContext = mask.getContext('2d'); if (!maskContext) throw new Error('Canvas alpha mask is unavailable'); maskContext.filter = `blur(${GROUND_TINT_EDGE_FEATHER_PX}px)`; maskContext.drawImage(texture, 0, 0, width, height); const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; const context = canvas.getContext('2d'); if (!context) throw new Error('Canvas texture compositor is unavailable'); context.filter = `brightness(${1 + GROUND_TINT_TEXTURE_CONTRAST * .15}) contrast(${1 + GROUND_TINT_TEXTURE_CONTRAST * .35})`; context.drawImage(texture, 0, 0, width, height); context.filter = 'none'; context.globalCompositeOperation = 'multiply'; context.fillStyle = gradient(context, colors, angleDegrees, width, height); context.fillRect(0, 0, width, height); context.globalCompositeOperation = 'destination-in'; context.drawImage(mask, 0, 0); return canvas; }
export function rasterizeGroundTintTexture(textureUrl: string, gradientColors: readonly string[], gradientAngleDegrees: number, width: number, height: number, transform?: Pick<GroundTintTextureLayer, 'rotationDegrees' | 'scaleX' | 'scaleY'>): Promise<HTMLCanvasElement> { const transformKey = transform ? `${transform.rotationDegrees}|${transform.scaleX}|${transform.scaleY}` : 'default'; const key = `${textureUrl}|${gradientColors.join(',')}|angle:${gradientAngleDegrees}|${width}x${height}|${transformKey}|contrast:${GROUND_TINT_TEXTURE_CONTRAST}|feather:${GROUND_TINT_EDGE_FEATHER_PX}`; const cached = rasterCache.get(key); if (cached) return cached; const pending = loadImage(textureUrl).then((texture) => { const tinted = composeTexture(texture, gradientColors, gradientAngleDegrees, width, height); const output = document.createElement('canvas'); output.width = width; output.height = height; const context = output.getContext('2d'); if (!context) throw new Error('Canvas raster output is unavailable'); context.translate(width / 2, height / 2); context.rotate((transform?.rotationDegrees ?? 0) * Math.PI / 180); context.scale(transform?.scaleX ?? 1, transform?.scaleY ?? 1); context.drawImage(tinted, -width / 2, -height / 2); return output; }); rasterCache.set(key, pending); return pending; }
export async function verifyGroundTintVisibility(): Promise<boolean> { const canvas = await rasterizeGroundTintTexture(TEXTURE_URLS[0], ['#f00', '#f00', '#f00'], 0, 252, 252); return canvas.width === 252 && canvas.height === 252; }
