import { useEffect } from 'react';
import { WORLD_ELEMENTS } from '../../config/worldElements';
import { MAP_STICKER_DISPLAY_PX, WORLD_ELEMENT_DWELL_MS, WORLD_ELEMENT_HEADING_OFFSET_DEG, WORLD_ELEMENT_RANDOM_SEED, WORLD_ELEMENT_SIZE_RATIO, WORLD_ELEMENT_SPAWN_RADIUS_METERS, WORLD_ELEMENT_TUNING, WORLD_ELEMENT_WAYPOINT_MAX_ATTEMPTS, WORLD_ELEMENT_WAYPOINT_MIN_SPACING_METERS, WORLD_ELEMENT_Z_INDEX } from '../../config/mapDemoTuning';
import type { GeoCoordinate } from '../../services/location/types';

interface Props { map: any; AMap: any; spawnCenter: GeoCoordinate; momentSpawnCenters: readonly GeoCoordinate[]; }
interface Sample { point: GeoCoordinate; distance: number; }
interface Roam { image: HTMLImageElement; size: number; points: GeoCoordinate[]; paths: Sample[][]; segment: number; phase: 'dwell' | 'travel'; phaseStartedAt: number; heading: number; speed: number; }

const meterLatitude = 111_320;
function offset(center: GeoCoordinate, east: number, north: number): GeoCoordinate { return { latitude: center.latitude + north / meterLatitude, longitude: center.longitude + east / (meterLatitude * Math.cos(center.latitude * Math.PI / 180)) }; }
function distance(a: GeoCoordinate, b: GeoCoordinate): number { return Math.hypot((b.latitude - a.latitude) * meterLatitude, (b.longitude - a.longitude) * meterLatitude * Math.cos(a.latitude * Math.PI / 180)); }
function random(seed: string) { let state = 2166136261; for (let i = 0; i < seed.length; i += 1) { state ^= seed.charCodeAt(i); state = Math.imul(state, 16777619); } return () => { state += 0x6D2B79F5; let value = state; value = Math.imul(value ^ value >>> 15, value | 1); value ^= value + Math.imul(value ^ value >>> 7, value | 61); return ((value ^ value >>> 14) >>> 0) / 4294967296; }; }
function randomNear(center: GeoCoordinate, radius: number, next: () => number) { const angle = next() * Math.PI * 2; const length = Math.sqrt(next()) * radius; return offset(center, Math.cos(angle) * length, Math.sin(angle) * length); }
function catmull(points: readonly GeoCoordinate[], segment: number, t: number): GeoCoordinate { const n = points.length; const at = (index: number) => points[(index + n) % n]; const [a, b, c, d] = [at(segment - 1), at(segment), at(segment + 1), at(segment + 2)]; const t2 = t * t; const t3 = t2 * t; const interpolate = (p0: number, p1: number, p2: number, p3: number) => .5 * (2 * p1 + (-p0 + p2) * t + (2 * p0 - 5 * p1 + 4 * p2 - p3) * t2 + (-p0 + 3 * p1 - 3 * p2 + p3) * t3); return { latitude: interpolate(a.latitude, b.latitude, c.latitude, d.latitude), longitude: interpolate(a.longitude, b.longitude, c.longitude, d.longitude) }; }
function pathFor(points: GeoCoordinate[], segment: number): Sample[] { const result: Sample[] = []; let total = 0; let previous: GeoCoordinate | undefined; for (let i = 0; i <= 36; i += 1) { const point = catmull(points, segment, i / 36); if (previous) total += distance(previous, point); result.push({ point, distance: total }); previous = point; } return result; }
function pointOn(path: Sample[], target: number) { const length = path[path.length - 1].distance; const wanted = Math.max(0, Math.min(length, target)); let before = path[path.length - 2]; let after = path[path.length - 1]; for (let i = 1; i < path.length; i += 1) if (wanted <= path[i].distance) { before = path[i - 1]; after = path[i]; break; } const fraction = after.distance === before.distance ? 0 : (wanted - before.distance) / (after.distance - before.distance); return { point: { latitude: before.point.latitude + (after.point.latitude - before.point.latitude) * fraction, longitude: before.point.longitude + (after.point.longitude - before.point.longitude) * fraction }, next: after.point }; }
function angle(previous: GeoCoordinate, current: GeoCoordinate, next: GeoCoordinate) { const a = distance(previous, current); const b = distance(current, next); const c = distance(previous, next); return a === 0 || b === 0 ? 0 : Math.acos(Math.max(-1, Math.min(1, (a * a + b * b - c * c) / (2 * a * b)))) * 180 / Math.PI; }
function valid(points: GeoCoordinate[]) { for (let i = 0; i < points.length; i += 1) { for (let j = i + 1; j < points.length; j += 1) if (distance(points[i], points[j]) < WORLD_ELEMENT_WAYPOINT_MIN_SPACING_METERS) return false; const turn = angle(points[(i - 1 + points.length) % points.length], points[i], points[(i + 1) % points.length]); if (turn < 30 || turn > 150) return false; } return true; }
function waypoints(center: GeoCoordinate, radius: number, next: () => number) { for (let attempt = 0; attempt < WORLD_ELEMENT_WAYPOINT_MAX_ATTEMPTS; attempt += 1) { const count = 3 + Math.floor(next() * 3); const points = Array.from({ length: count }, () => { const direction = next() * Math.PI * 2; const distanceFromCenter = radius * (.55 + Math.sqrt(next()) * .45); return { direction, point: offset(center, Math.cos(direction) * distanceFromCenter, Math.sin(direction) * distanceFromCenter) }; }).sort((a, b) => a.direction - b.direction).map((item) => item.point); if (valid(points)) return points; } const direction = next() * Math.PI * 2; return Array.from({ length: 4 }, (_, index) => offset(center, Math.cos(direction + index * Math.PI / 2) * radius * .7, Math.sin(direction + index * Math.PI / 2) * radius * .7)); }
function ease(progress: number) { return .5 - Math.cos(Math.PI * Math.max(0, Math.min(1, progress))) / 2; }

/** Canvas 自绘世界元素：不创建或移动任何 AMap.Marker。 */
export function WorldElementsLayer({ map, AMap, spawnCenter, momentSpawnCenters }: Props) {
  useEffect(() => {
    const canvas = document.createElement('canvas'); canvas.style.pointerEvents = 'none';
    const ctx = canvas.getContext('2d');
    if (!ctx || !AMap.CustomLayer) { console.error('[world] 当前高德实例未提供 CustomLayer，世界元素无法绘制。'); return undefined; }
    const roams: Roam[] = []; const centers = [spawnCenter, ...momentSpawnCenters]; const startedAt = performance.now();
    WORLD_ELEMENTS.forEach((spec) => { const tuning = WORLD_ELEMENT_TUNING[spec.id as keyof typeof WORLD_ELEMENT_TUNING]; if (!tuning) return; const size = spec.sizePx ?? MAP_STICKER_DISPLAY_PX * WORLD_ELEMENT_SIZE_RATIO; for (let index = 0; index < tuning.count; index += 1) { const next = random(`${WORLD_ELEMENT_RANDOM_SEED}:${spec.id}:${index}`); const origin = randomNear(centers[Math.floor(next() * centers.length)], WORLD_ELEMENT_SPAWN_RADIUS_METERS, next); if (spec.behavior !== 'roam') return; const points = waypoints(origin, tuning.roamRadiusMeters, next); const image = new Image(); image.src = spec.asset; roams.push({ image, size, points, paths: points.map((_, segment) => pathFor(points, segment)), segment: 0, phase: 'dwell', phaseStartedAt: startedAt, heading: WORLD_ELEMENT_HEADING_OFFSET_DEG, speed: tuning.speedMetersPerSec }); } });
    const resize = () => { const size = map.getSize(); const ratio = window.devicePixelRatio || 1; canvas.style.width = `${size.width}px`; canvas.style.height = `${size.height}px`; const width = Math.round(size.width * ratio); const height = Math.round(size.height * ratio); if (canvas.width !== width || canvas.height !== height) { canvas.width = width; canvas.height = height; } ctx.setTransform(ratio, 0, 0, ratio, 0, 0); return size; };
    const draw = (image: HTMLImageElement, size: number, point: GeoCoordinate, heading: number) => { if (!image.complete || image.naturalWidth === 0) return; const pixel = map.lngLatToContainer([point.longitude, point.latitude]); ctx.save(); ctx.translate(pixel.getX(), pixel.getY()); ctx.rotate(heading * Math.PI / 180); ctx.drawImage(image, -size / 2, -size / 2, size, size); ctx.restore(); };
    const render = () => { const viewport = resize(); ctx.clearRect(0, 0, viewport.width, viewport.height); const now = performance.now(); roams.forEach((roam) => { if (roam.speed <= 0) return; for (let transitions = 0; transitions < 8; transitions += 1) { const path = roam.paths[roam.segment]; const length = path[path.length - 1].distance; const travelMs = length / roam.speed * 1000; const elapsed = now - roam.phaseStartedAt; if (roam.phase === 'dwell') { if (elapsed < WORLD_ELEMENT_DWELL_MS) { draw(roam.image, roam.size, path[0].point, roam.heading); return; } roam.phase = 'travel'; roam.phaseStartedAt += WORLD_ELEMENT_DWELL_MS; continue; } if (elapsed >= travelMs) { roam.segment = (roam.segment + 1) % roam.points.length; roam.phase = 'dwell'; roam.phaseStartedAt += travelMs; continue; } const result = pointOn(path, length * ease(elapsed / travelMs)); const east = (result.next.longitude - result.point.longitude) * meterLatitude * Math.cos(result.point.latitude * Math.PI / 180); const north = (result.next.latitude - result.point.latitude) * meterLatitude; if (Math.hypot(east, north) > .001) roam.heading = -Math.atan2(north, east) * 180 / Math.PI + WORLD_ELEMENT_HEADING_OFFSET_DEG; draw(roam.image, roam.size, result.point, roam.heading); return; } }); };
    const layer = new AMap.CustomLayer(canvas, { render, alwaysRender: true, zIndex: WORLD_ELEMENT_Z_INDEX, zooms: [2, 20] });
    // 部分高德运行时在添加后才应用图层层级，显式重申与构造参数保持一致。
    if (typeof layer.setzIndex === 'function') layer.setzIndex(WORLD_ELEMENT_Z_INDEX);
    if (typeof map.addLayer === 'function') map.addLayer(layer); else map.add(layer);
    let frame = 0; const animate = () => { render(); frame = window.requestAnimationFrame(animate); }; frame = window.requestAnimationFrame(animate);
    return () => { window.cancelAnimationFrame(frame); if (typeof map.removeLayer === 'function') map.removeLayer(layer); else map.remove(layer); };
  }, [AMap, map, momentSpawnCenters, spawnCenter.latitude, spawnCenter.longitude]);
  return null;
}
