import { useEffect } from 'react';
import { WORLD_ELEMENTS } from '../../config/worldElements';
import { MAP_STICKER_DISPLAY_PX, WORLD_ELEMENT_DWELL_MS, WORLD_ELEMENT_HEADING_OFFSET_DEG, WORLD_ELEMENT_RANDOM_SEED, WORLD_ELEMENT_SIZE_RATIO, WORLD_ELEMENT_SPAWN_RADIUS_METERS, WORLD_ELEMENT_TUNING, WORLD_ELEMENT_Z_INDEX } from '../../config/mapDemoTuning';
import type { GeoCoordinate } from '../../services/location/types';
interface Props { map:any; AMap:any; spawnCenter:GeoCoordinate; momentSpawnCenters:readonly GeoCoordinate[]; }
interface Sample { point:GeoCoordinate; distance:number; } interface Roam { left:HTMLImageElement; right:HTMLImageElement; size:number; path:Sample[]; length:number; started:number; heading:number; speed:number; }
const M=111320, offset=(c:GeoCoordinate,e:number,n:number):GeoCoordinate=>({latitude:c.latitude+n/M,longitude:c.longitude+e/(M*Math.cos(c.latitude*Math.PI/180))}), dist=(a:GeoCoordinate,b:GeoCoordinate)=>Math.hypot((b.latitude-a.latitude)*M,(b.longitude-a.longitude)*M*Math.cos(a.latitude*Math.PI/180));
function rand(seed:string){let s=2166136261;for(const c of seed){s^=c.charCodeAt(0);s=Math.imul(s,16777619)}return()=>{s+=0x6D2B79F5;let v=s;v=Math.imul(v^v>>>15,v|1);v^=v+Math.imul(v^v>>>7,v|61);return((v^v>>>14)>>>0)/4294967296}}
function path(points:GeoCoordinate[]){const out:Sample[]=[];let total=0,prev:GeoCoordinate|undefined;for(let s=0;s<points.length;s++)for(let i=0;i<=36;i++){if(s&&i===0)continue;const n=points.length,at=(x:number)=>points[(x+n)%n],[a,b,c,d]=[at(s-1),at(s),at(s+1),at(s+2)],t=i/36,t2=t*t,t3=t2*t,f=(p0:number,p1:number,p2:number,p3:number)=>.5*(2*p1+(-p0+p2)*t+(2*p0-5*p1+4*p2-p3)*t2+(-p0+3*p1-3*p2+p3)*t3),p={latitude:f(a.latitude,b.latitude,c.latitude,d.latitude),longitude:f(a.longitude,b.longitude,c.longitude,d.longitude)};if(prev)total+=dist(prev,p);out.push({point:p,distance:total});prev=p}return out}
function pointAt(path:Sample[],wanted:number){let lo=1,hi=path.length-1;while(lo<hi){const m=(lo+hi)>>1;if(path[m].distance<wanted)lo=m+1;else hi=m}const a=path[lo],b=path[lo-1]??a,f=a.distance===b.distance?0:(wanted-b.distance)/(a.distance-b.distance);return{point:{latitude:b.point.latitude+(a.point.latitude-b.point.latitude)*f,longitude:b.point.longitude+(a.point.longitude-b.point.longitude)*f},next:a.point}}
const image=(src:string)=>{const i=new Image();i.src=src;return i}; const wrap=(n:number)=>((n+540)%360)-180;
export function WorldElementsLayer({map,AMap,spawnCenter,momentSpawnCenters}:Props){useEffect(()=>{const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');if(!ctx||!AMap.CustomLayer)return;const roams:Roam[]=[];WORLD_ELEMENTS.filter(x=>x.behavior==='roam').forEach(spec=>{const tune=WORLD_ELEMENT_TUNING[spec.id as keyof typeof WORLD_ELEMENT_TUNING];if(!tune)return;for(let k=0;k<tune.count;k++){const r=rand(`${WORLD_ELEMENT_RANDOM_SEED}:${spec.id}:${k}`),bases=[spawnCenter,...momentSpawnCenters],base=bases[Math.floor(r()*bases.length)],points=Array.from({length:4},(_,i)=>{const a=i*Math.PI/2+r()*.3,d=tune.roamRadiusMeters*(.65+r()*.25);return offset(base,Math.cos(a)*d,Math.sin(a)*d)}),p=path(points);roams.push({left:image('/world/butterfly-wing-left.png'),right:image('/world/butterfly-wing-right.png'),size:spec.sizePx??MAP_STICKER_DISPLAY_PX*WORLD_ELEMENT_SIZE_RATIO,path:p,length:p.at(-1)!.distance,started:performance.now(),heading:WORLD_ELEMENT_HEADING_OFFSET_DEG,speed:tune.speedMetersPerSec})}});const resize=()=>{const s=map.getSize(),r=devicePixelRatio||1;canvas.width=Math.round(s.width*r);canvas.height=Math.round(s.height*r);canvas.style.width=`${s.width}px`;canvas.style.height=`${s.height}px`;ctx.setTransform(r,0,0,r,0,0)};resize();map.on('resize',resize);const render=()=>{const s=map.getSize(),now=performance.now();ctx.clearRect(0,0,s.width,s.height);roams.forEach(roam=>{if(!roam.left.complete||!roam.right.complete)return;const travel=roam.length/roam.speed*1000,elapsed=(now-roam.started)%(travel+WORLD_ELEMENT_DWELL_MS),progress=elapsed<WORLD_ELEMENT_DWELL_MS?0:(elapsed-WORLD_ELEMENT_DWELL_MS)/travel,result=pointAt(roam.path,roam.length*progress),e=(result.next.longitude-result.point.longitude)*M*Math.cos(result.point.latitude*Math.PI/180),n=(result.next.latitude-result.point.latitude)*M;if(Math.hypot(e,n)>.001){const target=-Math.atan2(n,e)*180/Math.PI+WORLD_ELEMENT_HEADING_OFFSET_DEG;roam.heading+=wrap(target-roam.heading)*.15}const px=map.lngLatToContainer([result.point.longitude,result.point.latitude]),flap=.72+.28*Math.sin(now*.018);ctx.save();ctx.translate(px.getX(),px.getY());ctx.rotate(roam.heading*Math.PI/180);ctx.scale(flap,1);ctx.drawImage(roam.left,-roam.size,-roam.size/2,roam.size,roam.size);ctx.scale(-1,1);ctx.drawImage(roam.right,-roam.size,-roam.size/2,roam.size,roam.size);ctx.restore()})};const layer=new AMap.CustomLayer(canvas,{render,alwaysRender:true,zIndex:WORLD_ELEMENT_Z_INDEX,zooms:[2,20]});if(typeof map.addLayer==='function')map.addLayer(layer);else map.add(layer);return()=>{map.off('resize',resize);if(typeof map.removeLayer==='function')map.removeLayer(layer);else map.remove(layer)}},[AMap,map,momentSpawnCenters,spawnCenter.latitude,spawnCenter.longitude]);return null}
